set validation to False for Entrez.read()
This is necessary because of an unexpected error in Entrez parsing:

  File "/Users/lpritc/anaconda3/envs/phd_eastbio/lib/python3.8/site-packages/Bio/Entrez/__init__.py", line 487, in read
    record = handler.read(handle)
  File "/Users/lpritc/anaconda3/envs/phd_eastbio/lib/python3.8/site-packages/Bio/Entrez/Parser.py", line 345, in read
    self.parser.ParseFile(handle)
  File "/usr/local/miniconda/conda-bld/python_1584984502392/work/Modules/pyexpat.c", line 407, in StartElement
  File "/Users/lpritc/anaconda3/envs/phd_eastbio/lib/python3.8/site-packages/Bio/Entrez/Parser.py", line 607, in startElementHandler
    raise ValidationError(tag)
Bio.Entrez.Parser.ValidationError: Failed to find tag 'LatestAccession' in the DTD. To skip all tags that are not represented in the DTD, please call Bio.Entrez.read or Bio.Entrez.parse with validate=False.

The error is possibly due to the Biopython DTD not being current
with the NCBI returned XML.